// DPU_COMMON_ROOT 指向独立 dpu_common 仓库根目录，而不是其父目录。
+incdir+$DPU_COMMON_ROOT/src
+incdir+$HOST_MEM_ROOT/src
+incdir+../../pcie_tl_vip/src
+incdir+../../pcie_tl_vip/src/types
+incdir+../../pcie_tl_vip/src/shared
+incdir+../../pcie_tl_vip/src/agent
+incdir+../../pcie_tl_vip/src/env
+incdir+../../pcie_tl_vip/src/adapter
+incdir+../../pcie_tl_vip/src/seq/base
+incdir+../../pcie_tl_vip/src/seq/constraints
+incdir+../../pcie_tl_vip/src/seq/scenario
+incdir+../../pcie_tl_vip/src/seq/virtual
+incdir+../../pcie_tl_vip/src/switch
+incdir+../../pcie_tl_vip/src/topology
+incdir+../src
+incdir+../tests

$DPU_COMMON_ROOT/src/dpu_resource_pkg.sv
$HOST_MEM_ROOT/src/host_mem_pkg.sv
../../pcie_tl_vip/src/pcie_tl_if.sv
../../pcie_tl_vip/src/shared/pcie_tl_bdf_utils_pkg.sv
../../pcie_tl_vip/src/shared/pcie_tl_device_profile_pkg.sv
../../pcie_tl_vip/src/topology/pcie_topology_pkg.sv
../../pcie_tl_vip/src/pcie_tl_pkg.sv
../src/pcie_dpu_integration_pkg.sv
../src/pcie_dpu_tl_reg_executor.sv
../tests/pcie_dpu_tl_reg_executor_unit_test.sv
../tests/pcie_dpu_tl_reg_executor_tb_top.sv
