//------------------------------------------------------------------------------
// TL-root + 正式 SVT agent 双向门禁。
//
// 该测试把 SVT agent 作为 Serial transport 使用：链路控制由官方 SVT
// service sequence 完成，事务控制仍由 pcie_tl_env 发起。EP 侧手工返回一
// 个 Completion，用于验证 TL 请求经过 RC Mapper/Serial/EP Mapper 后，EP
// 再经过反向 Mapper/Serial 回到 TL RC driver，并完成 read-back。
//------------------------------------------------------------------------------

`include "uvm_macros.svh"

import uvm_pkg::*;
import pcie_tl_pkg::*;
import pcie_svt_adapter_pkg::*;

class pcie_tl_svt_formal_mem_rd_seq extends uvm_sequence #(pcie_tl_tlp);
  `uvm_object_utils(pcie_tl_svt_formal_mem_rd_seq)

  pcie_tl_mem_tlp request;

  function new(string name = "pcie_tl_svt_formal_mem_rd_seq");
    super.new(name);
  endfunction

  task body();
    request = pcie_tl_mem_tlp::type_id::create("request");
    request.kind = TLP_MEM_RD;
    request.type_f = TLP_TYPE_MEM_RD;
    request.fmt = FMT_3DW_NO_DATA;
    request.addr = 64'h0000_0000_0000_4000;
    request.length = 1;
    request.first_be = 4'hf;
    request.last_be = 4'h0;
    request.is_64bit = 1'b0;
    start_item(request);
    finish_item(request);
  endtask
endclass

// 只负责开启两端 Data Link Layer。PCIe 物理链路的训练和状态机由 SVT
// Serial HDL model 完成；TL 控制面在链路进入 L0 后才开始发包。
class pcie_tl_svt_formal_linkup_seq extends
    svt_pcie_device_system_virtual_base_sequence;
  `uvm_object_utils(pcie_tl_svt_formal_linkup_seq)
  `svt_xvm_declare_p_sequencer(svt_pcie_device_system_virtual_sequencer)

  function new(string name = "pcie_tl_svt_formal_linkup_seq");
    super.new(name);
  endfunction

  virtual task body();
    svt_pcie_dl_service_set_link_en_sequence root_link_en;
    svt_pcie_dl_service_set_link_en_sequence endpoint_link_en;

    root_link_en = svt_pcie_dl_service_set_link_en_sequence::type_id::create(
      "root_link_en");
    endpoint_link_en =
      svt_pcie_dl_service_set_link_en_sequence::type_id::create(
        "endpoint_link_en");
    root_link_en.enable = 1'b1;
    endpoint_link_en.enable = 1'b1;

    fork
      root_link_en.start(
        p_sequencer.root_virt_seqr.pcie_virt_seqr.dl_seqr);
      endpoint_link_en.start(
        p_sequencer.endpoint_virt_seqr.pcie_virt_seqr.dl_seqr);
    join
  endtask
endclass

class pcie_tl_svt_formal_link_test extends uvm_test;
  `uvm_component_utils(pcie_tl_svt_formal_link_test)

  // TL 是唯一控制面；SVT env 仅保存正式 transport agent。
  pcie_tl_env tl_env;
  pcie_tl_env_config tl_cfg;
  pcie_device_unified_vip_env svt_env;
  host_mem_manager root_mem;

  svt_pcie_device_configuration root_cfg;
  svt_pcie_device_configuration endpoint_cfg;
  svt_pcie_vif root_vif;
  svt_pcie_vif endpoint_vif;

  function new(string name = "pcie_tl_svt_formal_link_test",
               uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);

    // 官方 HDL interconnect 通过 config_db 发布 link_0_vif_0/1。
    void'(uvm_config_db#(svt_pcie_vif)::get(
      this, "", "link_0_vif_0", root_vif));
    void'(uvm_config_db#(svt_pcie_vif)::get(
      this, "", "link_0_vif_1", endpoint_vif));
    if ((root_vif == null) || (endpoint_vif == null))
      `uvm_fatal("SVT_FORMAL", "官方 Serial link virtual interface 未发布")

    root_cfg = svt_pcie_device_configuration::type_id::create(
      "root_cfg", this);
    endpoint_cfg = svt_pcie_device_configuration::type_id::create(
      "endpoint_cfg", this);
    root_cfg.set_initial_values_via_unified_vif(1, root_vif);
    endpoint_cfg.set_initial_values_via_unified_vif(1, endpoint_vif);

    // 诊断 SVT 配置对象的生命周期：FULL_VIP 的 TLP driver 在 pack 前
    // 必须拿到非空的 pcie_cfg.tl_cfg。若这里为空，说明问题发生在
    // set_initial_values_via_unified_vif/配置构造阶段，而不是 config_db
    // 路径或 adapter connect_phase。
    if (root_cfg.pcie_cfg == null)
      `uvm_fatal("SVT_FORMAL_CFG", "root_cfg.pcie_cfg 在初始化后为空")
    if (endpoint_cfg.pcie_cfg == null)
      `uvm_fatal("SVT_FORMAL_CFG", "endpoint_cfg.pcie_cfg 在初始化后为空")
    if (root_cfg.pcie_cfg.tl_cfg == null)
      `uvm_fatal("SVT_FORMAL_CFG", "root_cfg.pcie_cfg.tl_cfg 在初始化后为空")
    if (endpoint_cfg.pcie_cfg.tl_cfg == null)
      `uvm_fatal("SVT_FORMAL_CFG", "endpoint_cfg.pcie_cfg.tl_cfg 在初始化后为空")

    // TL env is the only configuration-space/BDF authority in this bridge.
    // The SVT global shadow database therefore does not contain the dynamic
    // requester functions generated by the TL sequences.  Disable only the
    // SVT shadow lookup check; this does not disable Serial, DL/PL, or the
    // adapter's TLP integrity path.  Users who intentionally populate SVT's
    // shadow configuration can override this policy in a dedicated test.
    root_cfg.pcie_cfg.tl_cfg.enable_shadow_cfg_lookup = 1'b0;
    endpoint_cfg.pcie_cfg.tl_cfg.enable_shadow_cfg_lookup = 1'b0;

    // Regression guard: keep the assignment above observable so a future
    // configuration refactor cannot silently reintroduce the warning.
    if (root_cfg.pcie_cfg.tl_cfg.enable_shadow_cfg_lookup ||
        endpoint_cfg.pcie_cfg.tl_cfg.enable_shadow_cfg_lookup)
      `uvm_fatal("SVT_FORMAL_CFG",
        "transport-only FULL_VIP requires shadow cfg lookup to be disabled")

    `uvm_info("SVT_FORMAL_CFG",
      "transport-only FULL_VIP: SVT shadow cfg lookup disabled", UVM_NONE)

    `uvm_info("SVT_FORMAL_CFG", $sformatf(
      "SVT TL cfg handles: root=%s endpoint=%s",
      root_cfg.pcie_cfg.tl_cfg.get_name(),
      endpoint_cfg.pcie_cfg.tl_cfg.get_name()), UVM_NONE)

    // 这里使用完整 SVT agent，而不是 RTL/Application Agent。后者的
    // tlp_mapper 只连接 DUT application interface，官方文档明确不会
    // 把事务送入 SVT 的 Serial PHY；FULL_VIP 才能证明本项目 adapter
    // 的 TLP 实际经过 DL/PL/Serial HDL interconnect。
    root_cfg.dut_model = svt_pcie_device_configuration::NOT_APPLICABLE;
    endpoint_cfg.dut_model = svt_pcie_device_configuration::NOT_APPLICABLE;

    // FULL_VIP 自带 Target App。为了验证“TL env 负责请求处理、SVT
    // 只负责 Serial/DL/PL transport”，将 Endpoint Target App 置于
    // Multi-Endpoint 的“未配置 BDF 不响应”策略：这样 incoming MRd
    // 仍会先由 SVT TL callback 旁路捕获，再进入本项目 EP driver，但不会
    // 与 pcie_tl_env 的 Completion 形成双响应。正式 DUT 集成时可以
    // 去掉该开关，由 DUT 自己实现 Target Completion。
    endpoint_cfg.pcie_cfg.enable_multi_endpoint_mode = 1'b1;
    endpoint_cfg.target_cfg[0].multi_ep_mode_resp_ctrl =
      svt_pcie_target_app_configuration::NO_RESP_IF_NO_FUNCTIONS_CONFIGURED;

    // 默认保留 PCIe 的常规 Gen1→最高速率协商。需要验证“直接从 Gen4
    // 起链”时，通过 +SVT_DIRECT_GEN4 将双方 supported/target/expected
    // 速率限制为 16 GT/s；filelist 已经编译 8G/16G 物理模型。
    if ($test$plusargs("SVT_DIRECT_GEN4")) begin
      // The unified VIF defaults to PCIe 3.0 for compatibility.  SVT rejects
      // a 16-GT/s supported-speed advertisement until the device-level spec
      // version is raised to at least 4.0, so update both device configs in
      // the same branch as the Gen4 speed mask.
      root_cfg.pcie_spec_ver =
        svt_pcie_device_configuration::PCIE_SPEC_VER_4_0;
      endpoint_cfg.pcie_spec_ver =
        svt_pcie_device_configuration::PCIE_SPEC_VER_4_0;
      // set_link_speed_values() takes a bit mask for the first argument,
      // not the numeric generation.  0x1E advertises Gen1..Gen4 (Gen1 is
      // mandatory), while target/expected are the Gen4 value itself.
      root_cfg.pcie_cfg.pl_cfg.set_link_speed_values(
        (`SVT_PCIE_SPEED_2_5G | `SVT_PCIE_SPEED_5_0G |
         `SVT_PCIE_SPEED_8_0G  | `SVT_PCIE_SPEED_16_0G),
        `SVT_PCIE_SPEED_16_0G,
        `SVT_PCIE_SPEED_16_0G);
      endpoint_cfg.pcie_cfg.pl_cfg.set_link_speed_values(
        (`SVT_PCIE_SPEED_2_5G | `SVT_PCIE_SPEED_5_0G |
         `SVT_PCIE_SPEED_8_0G  | `SVT_PCIE_SPEED_16_0G),
        `SVT_PCIE_SPEED_16_0G,
        `SVT_PCIE_SPEED_16_0G);

      // Use the SVT-supported direct speed-up mode.  The electrical
      // receiver-detect/TS handshake still starts at the mandatory Gen1 rate,
      // but equalization does not step through Gen2/Gen3 before switching to
      // Gen4.  This is the supported meaning of "direct Gen4" in R-2020.12.
      root_cfg.pcie_cfg.pl_cfg.set_link_eq_attribute_values(
        svt_pcie_pl_configuration::LINK_EQ_MODE_FULL_EQUALIZATION_REQUIRED,
        1'b1, 0);
      endpoint_cfg.pcie_cfg.pl_cfg.set_link_eq_attribute_values(
        svt_pcie_pl_configuration::LINK_EQ_MODE_FULL_EQUALIZATION_REQUIRED,
        1'b1, 0);
      `uvm_info("SVT_FORMAL_CFG",
        "SVT_DIRECT_GEN4: supported/target/expected speed = 16 GT/s",
        UVM_NONE)
    end

    // FULL_VIP 是 active agent，SVT 要求 is_active=1 时保持
    // pcie_cfg.enable_monitor=0；active agent 的 TL 接收使用
    // svt_pcie_tl.pre_tlp_out_put callback（适配器在 connect_phase 注册）。

    // 不启用官方随机 application traffic，避免与 TL 控制面抢占 Mapper。
    uvm_config_db#(svt_pcie_device_configuration)::set(
      this, "svt_env", "root_cfg", root_cfg);
    uvm_config_db#(svt_pcie_device_configuration)::set(
      this, "svt_env", "endpoint_cfg", endpoint_cfg);
    svt_env = pcie_device_unified_vip_env::type_id::create("svt_env", this);

    // 工厂覆盖必须发生在 TL env 创建之前。adapter 在 connect_phase 解析
    // svt_env.root/endpoint，并绑定正式 agent.tlp_mapper。
    pcie_tl_if_adapter::type_id::set_type_override(
      pcie_svt_if_adapter::get_type());
    uvm_config_db#(string)::set(
      this, "tl_env.rc_adapter_0", "svt_agent_path",
      "uvm_test_top.svt_env.root");
    uvm_config_db#(string)::set(
      this, "tl_env.ep_adapter", "svt_agent_path",
      "uvm_test_top.svt_env.endpoint");
    uvm_config_db#(string)::set(
      this, "tl_env.rc_adapter_0", "svt_backend_mode", "FULL_VIP");
    uvm_config_db#(string)::set(
      this, "tl_env.ep_adapter", "svt_backend_mode", "FULL_VIP");
    // svt_pcie_tlp 的 cfg 字段在 SVT 内部为 protected，adapter 通过
    // setup_cfg() 绑定；这里显式传入各自 agent 的 TL 配置，保证 RC/EP
    // 的 TLP 约束和实际 driver 配置保持一致。
    uvm_config_db#(svt_pcie_tl_configuration)::set(
      this, "tl_env.rc_adapter_0", "svt_tl_cfg", root_cfg.pcie_cfg.tl_cfg);
    uvm_config_db#(svt_pcie_tl_configuration)::set(
      this, "tl_env.ep_adapter", "svt_tl_cfg", endpoint_cfg.pcie_cfg.tl_cfg);
    uvm_config_db#(bit)::set(
      this, "tl_env", "pcie_svt_bridge_required", 1'b1);

    tl_cfg = pcie_tl_env_config::type_id::create("tl_cfg");
    // 外部 SVT transport 两个方向都走 SV interface；pcie_tl_env 的
    // bridge_required 也会强制这一模式，防止启动内部 TLM loopback。
    tl_cfg.if_mode = SV_IF_MODE;
    tl_cfg.rc_agent_enable = 1'b1;
    tl_cfg.ep_agent_enable = 1'b1;
    tl_cfg.num_rc = 1;
    tl_cfg.num_ep = 1;
    // FULL_VIP bridge 不走 pcie_tl_env 的内部 TLM loopback；开启该开关后，
    // 环境会把 EP monitor 经 Serial 收到的请求交给本项目 EP driver，
    // 由 EP driver 生成 Completion 再经反向 SVT Serial 返回 RC。
    tl_cfg.ep_auto_response = 1'b1;
    tl_cfg.scb_enable = 1'b0;
    tl_cfg.infinite_credit = 1'b1;
    // 为 EP→RC 的 DMA 读提供一个真实的 Root memory backend。PREMAP
    // 会预留一个有界 backing block；由于 Host allocator 默认可随机放置，
    // 测试在 run_phase 中从同一 manager 取得实际地址后再发起 DMA。
    tl_cfg.use_unified_mem = 1'b1;
    tl_cfg.mem_access_mode = PCIE_TL_MEM_PREMAP;
    tl_cfg.premap_size = 32'h0001_0000;
    root_mem = new("root_mem");
    uvm_config_db#(host_mem_api)::set(this, "tl_env", "host_mem", root_mem);
    uvm_config_db#(pcie_tl_env_config)::set(this, "tl_env", "cfg", tl_cfg);
    tl_env = pcie_tl_env::type_id::create("tl_env", this);
  endfunction

  task run_phase(uvm_phase phase);
    pcie_tl_svt_formal_mem_rd_seq rd;
    pcie_tl_svt_formal_linkup_seq linkup;

    phase.raise_objection(this);

    // 先由 SVT 官方 DL service sequence 同时开启 RC/EP，再等待双方
    // 完成 Serial 训练进入 L0。FULL_VIP 模式下这些 status 句柄有效；
    // 若用户误把 agent 配成 RTL，立即给出明确错误而不是空句柄崩溃。
    #10us;
    linkup = pcie_tl_svt_formal_linkup_seq::type_id::create("linkup");
    linkup.start(svt_env.sys_virt_seqr);

    if ((svt_env.root_status == null) ||
        (svt_env.root_status.pcie_status == null) ||
        (svt_env.root_status.pcie_status.pl_status == null) ||
        (svt_env.endpoint_status == null) ||
        (svt_env.endpoint_status.pcie_status == null) ||
        (svt_env.endpoint_status.pcie_status.pl_status == null)) begin
      `uvm_fatal("SVT_FORMAL", "FULL_VIP link status 未创建")
    end

    fork : wait_for_l0_or_timeout
      begin
        wait (svt_env.root_status.pcie_status.pl_status.link_up == 1'b1);
        wait (svt_env.endpoint_status.pcie_status.pl_status.link_up == 1'b1);
        wait (svt_env.root_status.pcie_status.pl_status.ltssm_state ==
              svt_pcie_types::L0);
        wait (svt_env.endpoint_status.pcie_status.pl_status.ltssm_state ==
              svt_pcie_types::L0);
        `uvm_info("SVT_FORMAL", "SVT_SERIAL_LINK_L0", UVM_NONE)
      end
      begin
        #500us;
        `uvm_fatal("SVT_FORMAL", "SVT Serial link-up timeout")
      end
    join_any
    disable wait_for_l0_or_timeout;

    // TL RC 发起一个读请求；driver 会在 finish_item 返回前分配 tag。
    rd = pcie_tl_svt_formal_mem_rd_seq::type_id::create("rd");
    rd.start(tl_env.v_seqr.rc_seqr);
    if (rd.request == null)
      `uvm_fatal("SVT_FORMAL", "TL read request 未生成")

    // 失败路径必须有限时退出；否则 Completion 丢失时测试会无限等待，
    // 无法区分“链路未通”和“请求已发但回包未返回”。
    fork : wait_for_completion_or_timeout
      begin
        wait (rd.request.rb_done == 1'b1);
      end
      begin
        #100us;
        `uvm_fatal("SVT_FORMAL", $sformatf(
          "SVT Serial Completion timeout: rb_done=%0b tag=0x%03h",
          rd.request.rb_done, rd.request.tag))
      end
    join_any
    disable wait_for_completion_or_timeout;
    if (rd.request.rb_data.size() == 0)
      `uvm_fatal("SVT_FORMAL", "SVT Serial Completion 没有返回 payload")

    `uvm_info("SVT_FORMAL", $sformatf(
      "PCIE_TL_SVT_TLP_PASS bytes=%0d first=0x%02h",
      rd.request.rb_data.size(), rd.request.rb_data[0]), UVM_NONE)

    // RC→EP posted write followed by read-back，确认请求和 Completion 都
    // 穿过 FULL_VIP Serial，而不是只验证固定的零数据 Completion。
    begin
      pcie_tl_rw_seq wr_seq;
      pcie_tl_rw_seq rd_seq;
      bit [7:0] pattern[];

      pattern = new[16];
      foreach (pattern[i]) pattern[i] = 8'hA0 + i;

      wr_seq = pcie_tl_rw_seq::type_id::create("formal_rc_write");
      wr_seq.op = PCIE_RW_WRITE;
      wr_seq.addr = 64'h0000_0000_0000_4000;
      wr_seq.byte_len = pattern.size();
      wr_seq.wdata = pattern;
      wr_seq.start(tl_env.v_seqr.rc_seqr);

      rd_seq = pcie_tl_rw_seq::type_id::create("formal_rc_readback");
      rd_seq.op = PCIE_RW_READ;
      rd_seq.addr = wr_seq.addr;
      rd_seq.byte_len = pattern.size();
      rd_seq.rb_timeout_ns = 100_000;
      rd_seq.start(tl_env.v_seqr.rc_seqr);
      if (rd_seq.status != PCIE_RW_OK)
        `uvm_fatal("SVT_FORMAL", "RC→EP read-back status 非 OK")
      foreach (pattern[i]) begin
        if ((i >= rd_seq.rdata.size()) || (rd_seq.rdata[i] != pattern[i]))
          `uvm_fatal("SVT_FORMAL", $sformatf(
            "RC→EP read-back mismatch index=%0d got=0x%02h exp=0x%02h",
            i, (i < rd_seq.rdata.size()) ? rd_seq.rdata[i] : 8'hxx,
            pattern[i]))
      end
      `uvm_info("SVT_FORMAL", "RC_EP_WRITE_READBACK_PASS bytes=16", UVM_NONE)
    end

    // EP→RC Non-Posted Read，验证新增的 RC ingress bridge FIFO、Root
    // unified-memory responder 以及反向 Completion。PREMAP 的 buddy
    // 分配从地址 0 开始，故这里读取该已分配窗口的确定性 pattern。
    begin
      pcie_tl_rw_seq ep_rd_seq;
      byte seed_data[];
      bit [63:0] read_addr;

      seed_data = new[16];
      foreach (seed_data[i]) seed_data[i] = 8'h50 + i;

      // Host memory uses the allocator's placement policy (random by
      // default), so address zero is not guaranteed to belong to the PREMAP
      // block.  Obtain a real allocation from the same manager that the RC
      // responder uses; this models the address a DPU/VIO descriptor would
      // carry in a real test.
      read_addr = root_mem.alloc(seed_data.size(), 16);
      if (read_addr == '1)
        `uvm_fatal("SVT_FORMAL", "无法为 EP→RC 读分配 Host memory 地址")
      root_mem.write_mem(read_addr, seed_data);

      ep_rd_seq = pcie_tl_rw_seq::type_id::create("formal_ep_read");
      ep_rd_seq.op = PCIE_RW_READ;
      ep_rd_seq.addr = read_addr;
      ep_rd_seq.byte_len = seed_data.size();
      ep_rd_seq.rb_timeout_ns = 100_000;
      ep_rd_seq.start(tl_env.v_seqr.ep_seqr);
      if (ep_rd_seq.status != PCIE_RW_OK)
        `uvm_fatal("SVT_FORMAL", "EP→RC read status 非 OK")
      foreach (seed_data[i]) begin
        if ((i >= ep_rd_seq.rdata.size()) ||
            (ep_rd_seq.rdata[i] != seed_data[i]))
          `uvm_fatal("SVT_FORMAL", $sformatf(
            "EP→RC read-back mismatch index=%0d got=0x%02h exp=0x%02h",
            i, (i < ep_rd_seq.rdata.size()) ? ep_rd_seq.rdata[i] : 8'hxx,
            seed_data[i]))
      end
      `uvm_info("SVT_FORMAL", "EP_RC_READBACK_PASS bytes=16", UVM_NONE)
      root_mem.free(read_addr);
    end

    // EP→RC Posted Write，验证反向请求不仅能读 Root host memory，也能
    // 经由 FULL_VIP Serial 到达 RC driver 并落入统一内存。Posted Write
    // 本身没有 Completion，因此由 testbench 在有限等待后回读 backing
    // store；若请求没有穿过 adapter 或 RC responder，该校验会直接失败。
    begin
      pcie_tl_rw_seq ep_wr_seq;
      byte write_data[];
      byte write_back[];
      bit [63:0] write_addr;

      write_data = new[16];
      foreach (write_data[i]) write_data[i] = 8'hC0 + i;

      // Posted writes must target an allocated range as well.  Using an
      // allocator-derived address keeps this check valid for both random and
      // deterministic Host memory placement policies.
      write_addr = root_mem.alloc(write_data.size(), 16);
      if (write_addr == '1)
        `uvm_fatal("SVT_FORMAL", "无法为 EP→RC 写分配 Host memory 地址")

      ep_wr_seq = pcie_tl_rw_seq::type_id::create("formal_ep_write");
      ep_wr_seq.op = PCIE_RW_WRITE;
      ep_wr_seq.addr = write_addr;
      ep_wr_seq.byte_len = write_data.size();
      ep_wr_seq.wdata = new[write_data.size()];
      foreach (write_data[i]) ep_wr_seq.wdata[i] = write_data[i];
      ep_wr_seq.start(tl_env.v_seqr.ep_seqr);

      // Serial/DL/PL 和 RC responder 都是异步路径；等待窗口仅用于保证
      // Posted Write 已经离开 transport，再检查 host memory 内容。
      #10us;
      root_mem.read_mem(write_addr, write_data.size(), write_back);
      foreach (write_data[i]) begin
        if ((i >= write_back.size()) || (write_back[i] != write_data[i]))
          `uvm_fatal("SVT_FORMAL", $sformatf(
            "EP→RC write mismatch index=%0d got=0x%02h exp=0x%02h",
            i, (i < write_back.size()) ? write_back[i] : 8'hxx,
            write_data[i]))
      end
      `uvm_info("SVT_FORMAL", "EP_RC_WRITE_PASS bytes=16", UVM_NONE)
      root_mem.free(write_addr);
    end

    phase.drop_objection(this);
  endtask
endclass
